"""init tabel pertama

Revision ID: 8cc53fe8dbc0
Revises: 
Create Date: 2026-03-27 17:49:38.572340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc53fe8dbc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('captured_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('feature_data', sa.LargeBinary(), nullable=True),
    sa.Column('feature_type', sa.String(length=10), nullable=True),
    sa.Column('shape_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('food_label', sa.String(length=100), nullable=False),
    sa.Column('is_known', sa.Boolean(), nullable=True),
    sa.Column('storage_type', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('days_remaining', sa.Float(), nullable=True),
    sa.Column('freshness_status', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decay_curve', sa.JSON(), nullable=True),
    sa.Column('predicted_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('food_sessions')
    op.drop_table('feature_cache')
    op.drop_table('daily_snapshots')
    # ### end Alembic commands ###
